name:  Android build on Ubuntu
on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop
jobs:
  install-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install npm dependencies
        run: |
          npm install
  build-android:
    needs: install-and-test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install npm dependencies
        run: |
          npm install
      - name: Build Android Release
        run: |
          cd android && ./gradlew assembleRelease
      - name: Upload Artifact
        uses: actions/upload-artifact@v1
        with:
          name: app-release.apk
          path: android/app/build/outputs/apk/release/

    - name: Upload Android APK to Browserstack
      run: |
        upload_file=TreeInventory-`echo $GITHUB_REF | awk '{split($0,a,"/"); print a[3]}'`.apk
        echo "::set-env name=upload_file::$upload_file"
        mv android/app/build/outputs/apk/develop/release/app-release.apk release/$upload_file
        curl -u "planetit1:${{ secrets.BROWSERSTACK_ACCESS_KEY }}" -X POST "https://api-cloud.browserstack.com/app-live/upload" -F "file=@release/$upload_file"
