name:  Android build on Ubuntu

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  install-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v2

      - name: Caching node modules
        uses: actions/cache@v1
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node2-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node2-

      - name: Install npm dependencies
        run: |
          npm install

  build-android:
    needs: install-and-test
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout branch
        uses: actions/checkout@v2

      - name: Caching node modules
        uses: actions/cache@v1
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node2-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node2-

      - name: Install npm dependencies
        run: |
          npm install

      - name: Setting Environment Variables
        env:
          MAPBOXGL_ACCCESS_TOKEN: ${{ secrets.MAPBOXGL_ACCCESS_TOKEN }}
        run: |
          echo "MAPBOXGL_ACCCESS_TOKEN=$MAPBOXGL_ACCCESS_TOKEN" >> .env

      - name: Preparing Android build
        env:
          android_release_password: ${{ secrets.ANDROID_RELEASE_PASSWORD }}
        run: |
          # react-native-i18n has an incompatible manifest
          search='<uses-sdk android:minSdkVersion="16" />'
          sed -i "s|${search}||g" node_modules/react-native-i18n/android/src/main/AndroidManifest.xml
          # prepare local.properties
          echo "MYAPP_RELEASE_STORE_PASSWORD=$android_release_password" > android/local.properties
          echo "MYAPP_RELEASE_KEY_PASSWORD=$android_release_password" >> android/local.properties

      - name: Fixes for Android Build
        run: |
          # fix problems with 'Error: ENOSPC: System limit for number of file watchers reached'
          echo fs.inotify.max_user_watches=524288 | sudo tee -a /etc/sysctl.conf && sudo sysctl -p
          # fix for task ':app:stripDevelopReleaseDebugSymbols'
          (echo y; echo y; echo y;) | sudo $ANDROID_HOME/tools/bin/sdkmanager  'ndk;20.0.5594570'

      - name: Caching Gradle dependencies
        uses: actions/cache@v1
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle2-${{ hashFiles('android/*.gradle') }}
          restore-keys: |
            ${{ runner.os }}-gradle2-

      - name: Build Android Release
        run: |
          cd android && ./gradlew assembleRelease

#      - name: Upload Artifact
#        uses: actions/upload-artifact@v1
#        with:
#          name: app-release.apk
#          path: android/app/build/outputs/apk/release/

      - name: Upload Android APK to Browserstack
        env:
          BROWSERSTACK_ACCESS_KEY: ${{ secrets.BROWSERSTACK_ACCESS_KEY }}
        run: |
          upload_file=TreeInventory-`echo $GITHUB_REF | awk '{split($0,a,"/"); print a[3]}'`.apk
          echo "::set-env name=upload_file::$upload_file"
          mv android/app/build/outputs/apk/release/app-release.apk $upload_file
          curl -u "planetit1:$BROWSERSTACK_ACCESS_KEY" -X POST "https://api-cloud.browserstack.com/app-live/upload" -F "file=@$upload_file"

      - name: Slack notification
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        run: |
          payload="{\"channel\": \"#notifications-git\", \"username\": \"webhookbot\", \"text\": \"Finished GitHub action $GITHUB_WORKFLOW for $GITHUB_REF (TreeInventory)\"}"
          curl -X POST --data-urlencode "payload=$payload" https://hooks.slack.com/services/$SLACK_WEBHOOK_URL
