name:  Test build on Ubuntu

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop
      - feature/tree_inventory

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
    - name: Checkout branch
      uses: actions/checkout@v2

    - name: Caching node modules
      uses: actions/cache@v1
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-treemapper-${{ hashFiles('package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-treemapper-

    - name: Install react-native CLI
      run: 'sudo npm install -g react-native-cli'

    - name: Install npm dependencies
      run: npm install

    - name: Linting
      run: npm run lint:errors || true

    - name: Setting Environment Variables
      env:
        MAPBOXGL_ACCCESS_TOKEN: ${{ secrets.MAPBOXGL_ACCCESS_TOKEN }}
        BUGSNAP_CLIENT_KEY: ${{ secrets.BUGSNAP_CLIENT_KEY }}
        AUTH0_DOMAIN: ${{ secrets.AUTH0_DOMAIN }}
        AUTH0_CLIENT_ID: ${{ secrets.AUTH0_CLIENT_ID }}
        API_ENDPOINT: ${{ secrets.API_ENDPOINT }}
      run: |
        echo "MAPBOXGL_ACCCESS_TOKEN=$MAPBOXGL_ACCCESS_TOKEN" >> .env
        echo "BUGSNAP_CLIENT_KEY=$BUGSNAP_CLIENT_KEY" >> .env
        echo "AUTH0_DOMAIN=$AUTH0_DOMAIN" >> .env
        echo "AUTH0_CLIENT_ID=$AUTH0_CLIENT_ID" >> .env
        echo "API_ENDPOINT=$API_ENDPOINT" >> .env

    - name: Build Android app
      run: |
        react-native bundle \
            --platform android \
            --dev false \
            --entry-file index.js \
            --bundle-output android-release.bundle \
            --sourcemap-output android-release.bundle.map
    - name: Build iOS app
      run: |
        react-native bundle \
            --platform ios \
            --dev false \
            --entry-file index.js \
            --bundle-output ios-release.bundle \
            --sourcemap-output ios-release.bundle.map
